import {
  Star,
  Coffee,
  Bean,
  CookingPot,
  CupSoda,
  Heart,
  Gift,
  Dog,
  Beer,
  Book,
  Car,
  Cat,
  Wine,
  Hamburger,
  UtensilsCrossed,
  IceCreamCone,
  Apple,
  Carrot,
  Candy,
  Bone,
  Flower2,
  PawPrint,
  Code,
  Beef,
  type LucideIcon,
} from "lucide-react";

export const STAMP_ICONS: Record<string, LucideIcon> = {
  star: Star,
  coffee: Coffee,
  coffeeBean: Bean,
  coffeePot: CookingPot,
  coffeeToGo: CupSoda,
  heart: Heart,
  gift: Gift,
  dog: Dog,
  beer: Beer,
  book: Book,
  car: Car,
  cat: Cat,
  wine: Wine,
  burger: Hamburger,
  food: UtensilsCrossed,
  iceCream: IceCreamCone,
  fruit: Apple,
  vegetables: Carrot,
  candy: Candy,
  bone: Bone,
  flower: Flower2,
  paw: PawPrint,
  code: Code,
  meat: Beef,
};

export const STAMP_ICON_KEYS = Object.keys(STAMP_ICONS);
